import ProviderWrappers from "@/components/ProviderWrappers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProviderWrappers>
      <body>{children}</body>
    </ProviderWrappers>
  );
}
