import "./globals.css";
import ProviderWrappers from "@/components/ProviderWrappers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderWrappers>
        <body>{children}</body>
      </ProviderWrappers>
    </html>
  );
}
